### ISSUE TITLE
Lab 1 - Change publish artifact code snipet 

### ISSUE THREAD

**Issue by fboucher** [MSDEVMTL/GlobalAzureBootcamp-2019#38]
In the section Continuous Deployment (https://github.com/MSDEVMTL/GlobalAzureBootcamp-2019/tree/master/Lab1#continuous-deployment)

We need to specify the subFolder `./GABDemo/` like explained in #37 

So the snippet (line 133)

```
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish $(buildConfiguration)'
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
```

should become

```
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish ./GABDemo/ $(buildConfiguration)'
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
```
